### ISSUE TITLE
Spread Penalty Issue

### ISSUE THREAD

**Issue by ArbanGarrera** [CeruleanAcorn/SRPG-Studio-Plugins#2]
Hi. I've found a bug with your Spread Penalty plugin. I put a skill that gives a -20 hit penalty on all of my bow-using classes when attacking from three spaces away. I've noticed that if their AI is set to approach, they won't move at all. They can attack, but only if one of my units is within two-three spaces (range of bows in my project) of the bow-user. They will not move from their space at all. I have checked and no other plugins cause this issue, it is solely because of the spread penalty plugin.

The custom parameter I have used is {hitPenalty: 20, distanceThreshold: 2}

**Comment by CeruleanAcorn** [comment]
Hello, thank you very much for reaching out! Unfortunately, I haven't been able to replicate the scenario you're getting where an enemy unit doesn't move with the skill. 

Here are some details about what I tried, and some questions/observations:
- You mentioned the hit penalty being applied to all bow-wielding classes in your project, so, on a freshly made SRPG Studio Project with no other plugins, I applied Spread Penalty as a class skill that both units have (with the same custom parameters you provided). 
- **I am wondering if you have checked the Range Only Checkbox in the Action Pattern area (where you can set the AI to approach)?** If the AI is set to Approach and this is NOT check marked, the enemy will move towards the player unit until they are in attacking range. However, if the AI is set to approach and this **is** check marked, then **yes**, the enemy will only move towards a player unit to attack if they are within attacking range, like how you described. 
- In all of the above cases, the enemy has either been able to both move and attack or simply attack without moving (the AI chooses to do this sometimes when, for example, the player unit they are attacking is already in their attack range). If a player unit moves to a tile adjacent to the enemy unit that enemy will move away to attack from 2-3 range.

I would suggest double-checking that the Range Only checkbox for the enemy AI in question hasn't been check marked so that enemies should try to approach your player units to attack. I also suggest that you test this in a new SRPG Studio project like I did if you haven't already (I know you've isolated the plugin on its own to check, but be sure to try it on an otherwise blank project anyways so we can be sure that it's not just the plugin causing this issue). You can find a demonstration of what I tried [here](https://drive.google.com/file/d/1pLvVA3mg6Dy7hKSDyDvaWdsyF8ET3fyO/view?usp=sharing), where I compare what happens when the Range Only checkbox is either checked or not.

**Comment by ArbanGarrera** [comment]
I created a new project with the Plugin and it had no effect on the AI of any bow-using class with approach. I checked and all bow-using classes with the approach AI in my project don't move, even if the range-only box is not checked. I have no idea what's causing the bug in my own project. One thing of note is that when I skip the enemy phase, the game lags when its the approaching bow-users' time to act. It's like the game doesn't know what to do and decides to give up and end their turn.

**Comment by CeruleanAcorn** [comment]
I've tried the plugin again with my new project by having a total of 4 enemy archers on the map and I don't get any slowdown or non-moving AI issues. I think we should try exchanging our newly-created projects to see if we can get each other's observed AI movement. If we are successful, then I can try to see if there is anything that is somehow different in both of our projects that is causing the issue for you but not me. Please find mine attached to this comment [here](https://github.com/CeruleanAcorn/SRPG-Studio-Plugins/files/10101006/TestingField.zip) and note that it was left in the state after the demo I showed it in; the plugin folder will only contain the latest version of my Spread Penalty plugin as of this comment, and the Range Only checkbox for the one enemy unit in the available map is checked so without unchecking it the enemy shouldn't approach you unless you move within their attacking range. 

Thank you for your note as well. The way you describe it, the game is having some sort of difficulty running the code in Spread Penalty for bow users quickly on your end (the code for calculating the new values of damage and hit altered by the skill will only run if the unit has said skill), hence the lag. I will try looking into possible reasons for this and how I might be able to make my code more efficient to run.

**Comment by ArbanGarrera** [comment]
Here is a link to a copy of my project. Thank you for helping me so far.

**Comment by CeruleanAcorn** [comment]
You're welcome, I'm happy to help however I can! I apologize for the very long response that follows, but I do want to be thorough in how I try helping you out. 

Apologies that I'm bringing this up after the fact, but I noticed the link you shared goes to what I assume isn't the new project you created with just the Spread Penalty Plugin after unzipping it, but another project. I realized that I might have actually misunderstood your earlier comment where you said:

> I created a new project with the Plugin and it had no effect on the AI of any bow-using class with approach. I checked and all bow-using classes with the approach AI in my project don't move, even if the range-only box is not checked. I have no idea what's causing the bug in my own project. 

I interpreted that as saying that you were still getting the same issue with the AI in the new blank project so was expecting that would be the project you sent. Did you actually mean that the plugin **didn't** cause the problem in the new project (so it worked like my project in the demo I sent), and the "I checked and all bow-using classes with the approach AI in my project don't move, even if the range-only box is not checked" statement only referred to your project in the Google Drive? I'm asking this partly because I think sending a project folder with all of your current progress and assets can be a big deal if there is something important you want to keep to yourself during development, and I don't wish to rummage so much through the inner workings of your project to respect that until I have your permission. I know that you sending me the link technically means you gave me permission, but I want to make sure that I'm not extensively going through something you mistakenly shared or didn't want seen. If I indeed interpreted that part of your comment wrong, I apologize for my misunderstanding.

**On the topic of continuing to narrow down your issue**, if it's true that in the new project you didn't get the AI issue with Spread Penalty and it's also true that in the Google Drive project you get the issue with Spread Penalty when adding it to your plugin folder, then finding out the root of the problem might come down to finding out if any of the other plugins are interacting with the Spread Penalty plugin that's causing this issue. You said you checked if other plugins were the issue and that it is solely because of Spread Penalty - how did you do it?  When it comes to figuring out if a plugin is causing unwanted behaviour in your project, I would suggest first checking by removing all other plugins except that one (Spread Penalty in this case) so it's the only one left your plugin folder (like in your new project) and test the game in that state if you haven't yet (it may be a bit redundant after testing Spread Penalty on its own in a new project but just to be extra careful you may as well try it in this project too). 

If after trying that the AI issue is **not** there, then as I mentioned it might mean there is some other plugin interacting with Spread Penalty that's causing the issues (known as "plugin clash", or "compability issues"). This can be quite the complicated problem sadly; I'm not sure how familiar you are with programming in SRPGS but essentially it's when two different plugins are trying to use the same particular section of code (or "function" to be specific) in the game engine, which can cause the game to run incorrectly or even crash. Goinza's GitHub page [has](https://github.com/Goinza/Plugins-for-SRPG-Studio#compatibility-issues) a good summary of this issue.  I don't have a lot of experience dealing with plugin clashing admittedly, but if I may please have permission to go through your project's current plugins, I can try to fix this for you by finding out which of them use the same functions as Spread Penalty and then testing how the AI works by leaving them in with Spread Penalty in the plugin folder one at a time until I find the pairing(s) that cause your AI issue, or you can try this process yourself, using the search bar on your computer's file explorer within the plugin folder to find the aforementioned plugins and searching the following lines:

DamageCalculator.calculateAttackPower
HitCalculator.calculateSingleHit
getDistanceFromTarget

In any case, if files causing the plugin clash are brought to your attention, ask yourself if they are currently necessary for your project's needs. If they are not, you can remove them so Spread Penalty will run without causing issues to your project; it is a good practice to not keep adding to your Plugins folder with plugins you don't need to use (you can also disable plugins in the plugin folder from being read by the game engine by adding a "$" to the start of their filename), so that you lower your risk of having unexpected plugin clashes in the future.

Lastly, do you happen to be in the SRPG Studio University Discord? This is a community where many SRPG Studio users, including SRPGS Plugin creators with far more experience making plugins than me, can converse about SRPG Studio. I would be happy to continue trying to help you until I'll be much less active on this GitHub and that Discord server for the rest of the year later this week, so they may be able to help you with this (if this isn't solved by then) and other issues while I'm absent. The community has been very helpful during my SRPG Studio journey. If you're interested, I can send you an invite link for you can reach out to them!

Thank you very much for reading through all this, and for your kind patience!

**Comment by ArbanGarrera** [comment]
> You said you checked if other plugins were the issue and that it is solely because of Spread Penalty - how did you do it? 

I moved all other plugins to a separate folder outside of my project folder. I tried out the game with only the spread penalty plugin and all bow-users with the approach AI still wouldn't move.

> Apologies that I'm bringing this up after the fact, but I noticed the link you shared goes to what I assume isn't the new project you created with just the Spread Penalty Plugin after unzipping it, but another project. I realized that I might have actually misunderstood your earlier comment where you said:
> 
> > I created a new project with the Plugin and it had no effect on the AI of any bow-using class with approach. I checked and all bow-using classes with the approach AI in my project don't move, even if the range-only box is not checked. I have no idea what's causing the bug in my own project.
> 
> I interpreted that as saying that you were still getting the same issue with the AI in the new blank project so was expecting that would be the project you sent. Did you actually mean that the plugin **didn't** cause the problem in the new project (so it worked like my project in the demo I sent), and the "I checked and all bow-using classes with the approach AI in my project don't move, even if the range-only box is not checked" statement only referred to your project in the Google Drive? I'm asking this partly because I think sending a project folder with all of your current progress and assets can be a big deal if there is something important you want to keep to yourself during development, and I don't wish to rummage so much through the inner workings of your project to respect that until I have your permission. I know that you sending me the link technically means you gave me permission, but I want to make sure that I'm not extensively going through something you mistakenly shared or didn't want seen. If I indeed interpreted that part of your comment wrong, I apologize for my misunderstanding.

Don't worry about it. I created a duplicate of my project and then zipped it. I intended to give you access to help with the problem. You have my full permission to go through my project if it helps solve the problem. Any changes you make to this will not effect my original project. The new blank project is completely unrelated to the one in the Google Drive link. And to clarify, in the new blank project, there were no issues with the plugin.

> Lastly, do you happen to be in the SRPG Studio University Discord? This is a community where many SRPG Studio users, including SRPGS Plugin creators with far more experience making plugins than me, can converse about SRPG Studio. I would be happy to continue trying to help you until I'll be much less active on this GitHub and that Discord server for the rest of the year later this week, so they may be able to help you with this (if this isn't solved by then) and other issues while I'm absent. The community has been very helpful during my SRPG Studio journey. If you're interested, I can send you an invite link for you can reach out to them!

Yes, I am on there. I went to you for help since you were the creator of the plugin and might have the best understanding of the issue. If things don't work out, I'll get help on the discord server.

I went and deleted all plugins with: 
DamageCalculator.calculateAttackPower
HitCalculator.calculateSingleHit
getDistanceFromTarget
The spread penalty plugin was still effecting the AI of the bow-users so they weren't causing the problem.

**Comment by CeruleanAcorn** [comment]
Thank you for your understanding, clarification, further testing, and permission to edit your project. 

I noticed something which I think is part of the key to this issue. In the Config tab, it appears that under "Game Options", both "Enemy AI attacks even if hit is 0" and "Enemy AI attacks even if atk is 0" are NOT checkmarked in project2 (by default they are). Testing out the AI of archer units, I wondered if they take Spread Penalty's penalties (in this case, the -20 hit penalty you described AND the default damage penalty of -25% per tile) into account when deciding to attack or not, but it seemed inconsistent, as enemies would still sometimes move around once within 2-3 range as you described, and attack from 3 range where their atk and/or hit rate are 0 after Spread Penalty is applied, even though they should have more than 0 if they attacked from 2 range. 

I'm unsure why the AI acts this way with Spread Penalty when the checkboxes are unchecked - it might have something to do with when the penalties are calculated and therefore used when determining how to move and/or attack. From a pattern I think I've noticed after messing around with weapon/unit stats, my guess is that if from its starting position an enemy's hit and/or atk are not 0 (depending on which of the boxes are checked), they might try to move and attack, resulting in it moving to a position where, because of Spread Penalty the stat(s) might be reduced to 0 in the end, breaking the desired effect of checking the box(es). Of note, I observed the actions of the AI without Spread Penalty on the archers I tested and no other plugins in the Plugin folder and it seems they stay completely still when the condition of either unchecked checkbox is met, even if in attacking range.

**If both of these boxes are CHECKED, the enemies will move toward the target normally as desired, technically fixing your problem, but this may be going against your intent for the AI in your project, and either way I want to figure out a way for Spread Penalty to work while still leaving those game options working correctly.**

Frankly, I hadn't considered these game options in the Config tab when developing this plugin. They will be something for me to analyze further, and I will turn to the SRPG Studio University Discord for further discussion on how to fix this issue. It's great to know you're part of the community already - perhaps we can further discuss there with some of the other Scripters you may already be familiar with. 

Thank you so much again for bringing this up to me, you've helped me discover things about the engine I will want to consider moving forward whenever I develop plugins like Spread Penalty.  I apologize for the difficulty this has caused you.

**Comment by ArbanGarrera** [comment]
I checked both "Enemy AI attacks even if hit is 0" and "Enemy AI attacks even if atk is 0" boxes and the bow-users with the approach AI now work properly. I unchecked them because I thought it would make the enemies smarter and more challenging, something I desired from my project, but it shouldn't bother to me too much. Thank you so much for your help. I'm glad I was able to help you understand more about the engine.
